### ISSUE TITLE
Enhance UI: Improve Buttons on /update Page

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Student_Database_COSA#24]
### Issue Description
The current UI of buttons on the `/update` page needs improvement for a better user experience. This issue is raised to discuss and implement enhancements to the button design.

### Areas for Improvement
- Provide details on specific buttons or aspects of the UI that need enhancement.
- Consider adding visual elements, such as icons or styling, to make buttons more intuitive.

**Comment by devloves** [comment]
I would be open to take this

**Comment by devloves** [comment]
why is the app not using bootstrap if its in the packages

**Comment by devloves** [comment]
am i allowed to use it or do i keep it purely CSS

**Comment by devloves** [comment]
![image](https://github.com/OpenLake/Student_Database_COSA/assets/65783463/cd374944-46a9-4239-b423-d24dc040f541)
![image](https://github.com/OpenLake/Student_Database_COSA/assets/65783463/a9b85675-99b2-4ab5-b6b5-da867458cb24)
![image](https://github.com/OpenLake/Student_Database_COSA/assets/65783463/ae1ca57c-2537-4cfa-b9ea-03750d947bb4)
![image](https://github.com/OpenLake/Student_Database_COSA/assets/65783463/b9591cc7-5606-4d08-b648-c2f0316b043e)
![image](https://github.com/OpenLake/Student_Database_COSA/assets/65783463/44d5d825-d310-4cc7-a365-eb285505e8d1)

**Comment by devloves** [comment]
Here is my finished design, ready to open a pull request if this looks right to you

**Comment by krishnan05** [comment]
> Here is my finished design, ready to open a pull request if this looks right to you

Looks good to me, can you just change the default POR type to show select instead of academic por in this PR itself

**Comment by devloves** [comment]
> > Here is my finished design, ready to open a pull request if this looks right to you
> 
> Looks good to me, can you just change the default POR type to show select instead of academic por in this PR itself

Done that

**Comment by krishnan05** [comment]
> > > Here is my finished design, ready to open a pull request if this looks right to you
> > 
> > 
> > Looks good to me, can you just change the default POR type to show select instead of academic por in this PR itself
> 
> Done that

Okay. Go ahead

**Comment by DevilsAutumn** [comment]
So, we have 2 PRs for this issue, #26 and #29 .

**Comment by devloves** [comment]
as i can see it was assigned to me
