### ISSUE TITLE
Implement Pre-commit Hooks for Code Quality

### ISSUE THREAD

**Issue by krishnan05** [OpenLake/Student_Database_COSA#25]
### Issue Description
This issue is raised to discuss and implement pre-commit hooks in our project to ensure and enforce code quality standards before a commit is made. Pre-commit hooks help catch issues early in the development process and maintain a consistent codebase.

### Goals
- Implement pre-commit hooks for code linting, formatting, and other relevant checks.
- Ensure that all contributors have a consistent development environment.
-
### Additional Information
- Any specific coding standards or guidelines that pre-commit hooks should enforce.
- Consideration for the impact on the development workflow.

**Comment by Snehil-Shah** [comment]
Can I work on this?
